# Generated by Django 2.0.1 on 2018-02-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('apple', 'apple'), ('orange', 'orange'), ('pineapple', 'pineapple'), ('banan', 'banan'), ('melon', 'melon')], default='apple', max_length=50),
            preserve_default=False,
        ),
    ]
